version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run Tests
          command: ./gradlew check test
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results
