/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jp.sane.numbertovietnamese

import kotlin.test.Test
import kotlin.test.assertSame

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertSame(true, classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
